language: java
jdk:
  - openjdk11

services:
  - docker

jobs:
  include:
    # IDEA inspections
    - name: "Run IntelliJ IDEA inspections"
      script:
        - echo "Maven version:" && ./mvnw --version
        - echo "Java version:" && java --version
        - echo "IDEA version:" && echo $IDEA_VERSION
        - mkdir .idea
        - cp config/intellij-idea-inspections-misc.xml .idea/misc.xml
        - ./.ci/idea-inspection.sh
      addons:
        artifacts:
          paths:
            - target/inspection-results

    # Maven validation examples
    - name: "no-exception-lucene-and-others-javadoc"
      script:
        - ./.ci/no-exception-test.sh no-exception-lucene-and-others-javadoc

    - name: "no-error-xwiki"
      jdk: openjdk18
      script:
        - ./.ci/validation.sh no-error-xwiki

    - name: "no-exception-spotbugs"
      script:
        - ./.ci/validation.sh no-exception-spotbugs

    # YAML Lint
    - name: "Yamllint"
      language: python
      before_install:
        - sudo apt update
        - sudo apt install -y yamllint
      script:
        - yamllint -f parsable -c config/yamllint.yaml .

    # Git validation
    - name: "git-no-merge-commits"
      script:
        - ./.ci/validation.sh git-no-merge-commits

    - name: "git-check-pull-number"
      script:
        - ./.ci/validation.sh git-check-pull-number
